import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{ type: 'autogenerated', dirName: '.' }],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
  //   tutorialSidebar: [
  //     'index',
  //     {
  //       type: 'category',
  //       label: '🚀 Getting Started',
  //       items: [
  //         'getting-started/overview',
  //         'getting-started/installation',
  //         'getting-started/first-steps',
  //         'getting-started/project-structure',
  //       ],
  //     },
  //     {
  //       type: 'category',
  //       label: '⚙️ Configuration',
  //       items: [
  //         'configuration/environment',
  //         'configuration/database',
  //         'configuration/authentication',
  //         'configuration/email',
  //         'configuration/oauth',
  //         'configuration/application-settings',
  //       ],
  //     },
  //     {
  //       type: 'category',
  //       label: '🎨 Customization',
  //       items: [
  //         'customization/theming',
  //         'customization/branding',
  //         'customization/categories',
  //         'customization/email-templates',
  //         'customization/components',
  //       ],
  //     },
  //     {
  //       type: 'category',
  //       label: '🚀 Deployment',
  //       items: [
  //         'deployment/overview',
  //         'deployment/vercel',
  //         'deployment/railway',
  //         'deployment/docker',
  //         'deployment/self-hosted',
  //         'deployment/production-checklist',
  //       ],
  //     },
  //     {
  //       type: 'category',
  //       label: '👨‍💼 Administration',
  //       items: [
  //         'administration/admin-panel',
  //         'administration/user-management',
  //         'administration/category-management',
  //         'administration/thread-moderation',
  //         'administration/reports',
  //         'administration/analytics',
  //       ],
  //     },
  //     {
  //       type: 'category',
  //       label: '🔧 Development',
  //       items: [
  //         'development/contributing',
  //         'development/architecture',
  //         'development/database-schema',
  //         'development/api-reference',
  //         'development/components',
  //         'development/testing',
  //       ],
  //     },
  //     {
  //       type: 'category',
  //       label: '📚 Guides',
  //       items: [
  //         'guides/user-guide',
  //         'guides/moderator-guide',
  //         'guides/migration',
  //         'guides/backup-restore',
  //         'guides/troubleshooting',
  //       ],
  //     },
  //     {
  //       type: 'category',
  //       label: '🆘 Help & Support',
  //       items: [
  //         'support/faq',
  //         'support/community',
  //         'support/issues',
  //         'support/changelog',
  //       ],
  //     },
  //   ],
};

export default sidebars;
